import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// HTTPS dev cert (gitignored, generated by scripts/setup-dev-tls.mjs via
// the predev hook). Required because the __Host- session cookie prefix
// only works over HTTPS; the SPA and Worker must both serve HTTPS so the
// browser will accept and send the cookie across the proxy.
const tlsDir = resolve(__dirname, '../../.dev-tls')
const httpsConfig = {
  key: readFileSync(resolve(tlsDir, 'localhost-key.pem')),
  cert: readFileSync(resolve(tlsDir, 'localhost.pem'))
}

// Vite dev server (5173, HTTPS) proxies API / MCP / OAuth / collab traffic
// to the local Worker (wrangler dev on 8787, HTTPS). `secure: false` lets
// the proxy trust the same locally-signed cert; `changeOrigin: true`
// rewrites the Host header so the Worker sees its own origin and signed
// cookies round-trip. WS upgrade via `ws: true` for /collab.
const workerTarget = 'https://localhost:8787'
const proxyEntry = { target: workerTarget, changeOrigin: true, secure: false }
const wsProxyEntry = { ...proxyEntry, ws: true }

export default defineConfig({
  plugins: [react()],
  server: {
    port: 5173,
    https: httpsConfig,
    proxy: {
      '/api': proxyEntry,
      '/oauth': proxyEntry,
      '/idp': proxyEntry,
      '/mcp': proxyEntry,
      '/sse': proxyEntry,
      '/collab': wsProxyEntry,
      '/.well-known': proxyEntry
    }
  },
  build: {
    outDir: 'dist',
    emptyOutDir: true,
    sourcemap: true
  }
})
