/**
 * MCP-spec OAuth provider for outbound `user_oauth` upstreams.
 *
 * Implements `OAuthClientProvider` from `@modelcontextprotocol/sdk` so we
 * can hand it to the SDK's `auth(...)` orchestrator. The SDK then drives
 * RFC 9728 discovery, RFC 7591 dynamic client registration, PKCE setup,
 * code → token exchange, and refresh; we just supply storage.
 *
 * Storage layout:
 *   - **Client info** (DCR result) lives in `upstream_servers.auth_config.oauth`
 *     and is shared across all users for that upstream (one registered client
 *     per upstream, not per user).
 *   - **PKCE verifier + flow context** lives in `OAUTH_KV` under
 *     `outbound:verifier:<state>` with a 10-minute TTL. The state token is
 *     generated by this provider's `state()` and used as the KV key, so the
 *     callback handler can look up `{verifier, userId, upstreamId}` from
 *     just the `?state=` query param.
 *   - **Tokens** (access + refresh + expires_at) are sealed via
 *     `crypto/aead.ts` and stored as a JSON blob in `user_credentials`
 *     with `kind = 'oauth'`. No schema migration needed.
 *
 * Two entry-point shapes:
 *   - `startFlow`: no state token yet; provider generates one. The start
 *     route calls `auth(provider, {serverUrl})`, then 302s to
 *     `provider.capturedRedirect`.
 *   - `completeFlow(state)`: state token from the callback URL; provider
 *     reads the verifier from KV. The callback route calls
 *     `auth(provider, {serverUrl, authorizationCode})`.
 *   - `refreshIfNeeded`: per-request use from the proxy registry. Calls
 *     `auth(provider, {serverUrl})` which transparently refreshes when
 *     tokens are stale, then returns the current access token.
 */

import type { OAuthClientProvider } from '@modelcontextprotocol/sdk/client/auth.js'
import type {
  OAuthClientInformationFull,
  OAuthClientInformationMixed,
  OAuthClientMetadata,
  OAuthTokens
} from '@modelcontextprotocol/sdk/shared/auth.js'
import type { Env } from '../env'
import { openStoredTokens, prepareStoredTokens } from './oauth-tokens'
import { patchUpstream, type UpstreamServerRow } from '../db/queries/upstreams'
import {
  clearReauthRequired,
  getUserCredential,
  upsertUserCredential
} from '../db/queries/upstream-credentials'
import type { UpstreamAuthConfig } from '@ctxlayer/shared'

const VERIFIER_TTL_SECONDS = 600
const REDIRECT_PATH = '/api/upstreams/oauth/callback'

/**
 * Where to bounce the user after the callback completes. Constrained
 * to the names we know — never accept a raw URL from the client.
 */
export type OAuthReturnTarget = 'user' | 'admin'

interface StoredVerifier {
  verifier: string
  userId: string
  upstreamId: string
  /** Defaults to 'user' (i.e. /upstreams) when absent for older rows. */
  returnTo?: OAuthReturnTarget
  createdAt: number
}

interface OAuthAuthConfig {
  client_id?: string
  client_secret?: string
  /** Persisted full DCR response so re-running auth() restores all metadata. */
  client_info?: OAuthClientInformationFull
}

export class UpstreamOAuthProvider implements OAuthClientProvider {
  private stateToken: string | null = null
  capturedRedirect: URL | null = null

  constructor(
    private readonly env: Env,
    private readonly upstream: UpstreamServerRow,
    private readonly userId: string,
    /**
     * On the callback path, pass the `?state=` value so we can read the
     * verifier KV row the start path wrote. On the start path leave this
     * undefined — `state()` generates a fresh token.
     */
    presetState?: string,
    /**
     * Persisted in the KV verifier row so the callback knows where to
     * send the user back. Only consulted on the start path; the callback
     * reads its own copy via `readVerifierState`.
     */
    private readonly returnTo?: OAuthReturnTarget
  ) {
    if (presetState) this.stateToken = presetState
  }

  // ----- where the redirect lands ---------------------------------------

  get redirectUrl(): string {
    // Single callback for all upstreams. We look up the (user, upstream)
    // pair from the state token in KV. The redirect_uri sent to the
    // upstream must match this exactly during DCR.
    return new URL(REDIRECT_PATH, this.env.PUBLIC_BASE_URL).toString()
  }

  get clientMetadata(): OAuthClientMetadata {
    return {
      client_name: 'ctxlayer',
      redirect_uris: [this.redirectUrl],
      grant_types: ['authorization_code', 'refresh_token'],
      response_types: ['code'],
      token_endpoint_auth_method: 'none',
      scope: this.preferredScope() ?? undefined
    }
  }

  // ----- state (PKCE / CSRF token) --------------------------------------

  state(): string {
    if (!this.stateToken) this.stateToken = crypto.randomUUID()
    return this.stateToken
  }

  async saveCodeVerifier(verifier: string): Promise<void> {
    const state = this.state()
    const stored: StoredVerifier = {
      verifier,
      userId: this.userId,
      upstreamId: this.upstream.id,
      returnTo: this.returnTo,
      createdAt: Math.floor(Date.now() / 1000)
    }
    await this.env.OAUTH_KV.put(verifierKey(state), JSON.stringify(stored), {
      expirationTtl: VERIFIER_TTL_SECONDS
    })
  }

  async codeVerifier(): Promise<string> {
    const state = this.state()
    const raw = await this.env.OAUTH_KV.get(verifierKey(state))
    if (!raw) throw new Error('oauth_verifier_missing_or_expired')
    const parsed = JSON.parse(raw) as StoredVerifier
    return parsed.verifier
  }

  // ----- client info (DCR) ---------------------------------------------

  async clientInformation(): Promise<OAuthClientInformationMixed | undefined> {
    const cfg = parseAuthConfig(this.upstream.auth_config)
    return cfg.oauth?.client_info as OAuthClientInformationMixed | undefined
  }

  async saveClientInformation(info: OAuthClientInformationFull): Promise<void> {
    const cfg = parseAuthConfig(this.upstream.auth_config)
    const nextOauth: OAuthAuthConfig = {
      ...(cfg.oauth ?? {}),
      client_info: info,
      client_id: info.client_id,
      client_secret: info.client_secret
    }
    const nextConfig: UpstreamAuthConfig = {
      ...cfg,
      // We store oauth client info as a typed-but-loose record alongside
      // the existing UpstreamAuthConfig fields. The shared schema knows
      // about `oauth: OauthAuthConfig` but its required fields don't match
      // what DCR returns (authorizeUrl/tokenUrl are server-discovered, not
      // admin-configured here). Keep the loose write — admin form never
      // round-trips this branch.
      oauth: nextOauth as unknown as UpstreamAuthConfig['oauth']
    }
    await patchUpstream(this.env, this.upstream.id, { authConfig: nextConfig })
    // Keep our in-memory row in sync for the rest of this request.
    this.upstream.auth_config = JSON.stringify(nextConfig)
  }

  // ----- tokens --------------------------------------------------------

  async tokens(): Promise<OAuthTokens | undefined> {
    const cred = await getUserCredential(this.env, this.userId, this.upstream.id)
    if (!cred || cred.kind !== 'oauth') return undefined
    return openStoredTokens(
      this.env,
      { ciphertext: cred.ciphertext, iv: cred.iv, keyVersion: cred.key_version },
      `oauth tokens decrypt failed for upstream ${this.upstream.slug}`
    )
  }

  async saveTokens(tokens: OAuthTokens): Promise<void> {
    // prepareStoredTokens carries the prior refresh_token (+ scope) forward
    // when a refresh response omits them. Providers commonly return ONLY a
    // new access_token on refresh and keep the existing refresh_token valid;
    // blindly overwriting with `undefined` DESTROYS our ability to refresh
    // again, leaving the upstream permanently needing interactive re-auth.
    // That was the Linear user_oauth death: a refresh that didn't re-issue
    // a refresh_token wiped ours → next refresh impossible → -32002. The
    // prior creds are only read when we actually need to backfill.
    const { sealed, merged } = await prepareStoredTokens(this.env, tokens, () => this.tokens())
    // Grant-level observability — metadata only, NO token values (per the
    // no-token-logging rule). Low-volume (only on a token grant/refresh).
    console.log(
      `[oauth] ${this.upstream.slug} saveTokens: has_refresh=${!!tokens.refresh_token} ` +
        `kept_prior_refresh=${!tokens.refresh_token && !!merged.refresh_token} ` +
        `expires_in=${tokens.expires_in ?? 'absent'}`
    )
    await upsertUserCredential(this.env, this.userId, this.upstream.id, {
      kind: 'oauth',
      ciphertext: sealed.ciphertext,
      iv: sealed.iv,
      keyVersion: sealed.keyVersion
    })
    // A fresh token landed — clear any pending re-auth flag (covers refresh
    // success, static refresh, the initial code exchange, and reconnect).
    await clearReauthRequired(this.env, this.userId, this.upstream.id)
  }

  // ----- redirect ------------------------------------------------------

  redirectToAuthorization(authorizationUrl: URL): void {
    // Capture for the HTTP handler to read after `auth()` returns
    // 'REDIRECT'. We can't actually redirect from inside a Worker
    // — we must return a 302 from the route layer.
    this.capturedRedirect = authorizationUrl
  }

  // ----- helpers -------------------------------------------------------

  private preferredScope(): string | null {
    const cfg = parseAuthConfig(this.upstream.auth_config)
    return cfg.oauth?.scopes?.join(' ') || null
  }
}

// ----- module-level helpers for routes --------------------------------

export async function readVerifierState(
  env: Env,
  stateToken: string
): Promise<StoredVerifier | null> {
  const raw = await env.OAUTH_KV.get(verifierKey(stateToken))
  return raw ? (JSON.parse(raw) as StoredVerifier) : null
}

export async function deleteVerifierState(env: Env, stateToken: string): Promise<void> {
  await env.OAUTH_KV.delete(verifierKey(stateToken))
}

function verifierKey(state: string): string {
  return `outbound:verifier:${state}`
}

// Re-exported from oauth-tokens.ts (its home since the git flow shares it);
// existing importers and tests keep this path.
export { mergeRefreshableTokens } from './oauth-tokens'

function parseAuthConfig(json: string): UpstreamAuthConfig {
  if (!json) return {}
  try {
    return JSON.parse(json) as UpstreamAuthConfig
  } catch {
    return {}
  }
}
