/**
 * MCP-spec OAuth provider for outbound `user_oauth` upstreams.
 *
 * Implements `OAuthClientProvider` from `@modelcontextprotocol/sdk` so we
 * can hand it to the SDK's `auth(...)` orchestrator. The SDK then drives
 * RFC 9728 discovery, RFC 7591 dynamic client registration, PKCE setup,
 * code → token exchange, and refresh; we just supply storage.
 *
 * Storage layout:
 *   - **Client info** (DCR result) lives in `upstream_servers.auth_config.oauth`
 *     and is shared across all users for that upstream (one registered client
 *     per upstream, not per user).
 *   - **PKCE verifier + flow context** lives in `OAUTH_KV` under
 *     `outbound:verifier:<state>` with a 10-minute TTL. The state token is
 *     generated by this provider's `state()` and used as the KV key, so the
 *     callback handler can look up `{verifier, userId, upstreamId}` from
 *     just the `?state=` query param.
 *   - **Tokens** (access + refresh + expires_at) are sealed via
 *     `crypto/aead.ts` and stored as a JSON blob in `user_credentials`
 *     with `kind = 'oauth'`. No schema migration needed.
 *
 * Two entry-point shapes:
 *   - `startFlow`: no state token yet; provider generates one. The start
 *     route calls `auth(provider, {serverUrl})`, then 302s to
 *     `provider.capturedRedirect`.
 *   - `completeFlow(state)`: state token from the callback URL; provider
 *     reads the verifier from KV. The callback route calls
 *     `auth(provider, {serverUrl, authorizationCode})`.
 *   - `refreshIfNeeded`: per-request use from the proxy registry. Calls
 *     `auth(provider, {serverUrl})` which transparently refreshes when
 *     tokens are stale, then returns the current access token.
 */

import type { OAuthClientProvider } from '@modelcontextprotocol/sdk/client/auth.js'
import type {
  OAuthClientInformationFull,
  OAuthClientInformationMixed,
  OAuthClientMetadata,
  OAuthTokens
} from '@modelcontextprotocol/sdk/shared/auth.js'
import type { Env } from '../env'
import { open as openSecret, seal as sealSecret } from '../crypto/aead'
import {
  getUserCredential,
  patchUpstream,
  upsertUserCredential,
  type UpstreamServerRow
} from '../db/queries/upstreams'
import type { UpstreamAuthConfig } from '@ctxlayer/shared'

const VERIFIER_TTL_SECONDS = 600
const REDIRECT_PATH = '/api/upstreams/oauth/callback'

interface StoredVerifier {
  verifier: string
  userId: string
  upstreamId: string
  createdAt: number
}

interface StoredOAuthTokens {
  access_token: string
  token_type?: string
  refresh_token?: string
  scope?: string
  /** Absolute unix seconds for when the access token expires. */
  expires_at?: number
}

interface OAuthAuthConfig {
  client_id?: string
  client_secret?: string
  /** Persisted full DCR response so re-running auth() restores all metadata. */
  client_info?: OAuthClientInformationFull
}

export class UpstreamOAuthProvider implements OAuthClientProvider {
  private stateToken: string | null = null
  capturedRedirect: URL | null = null

  constructor(
    private readonly env: Env,
    private readonly upstream: UpstreamServerRow,
    private readonly userId: string,
    /**
     * On the callback path, pass the `?state=` value so we can read the
     * verifier KV row the start path wrote. On the start path leave this
     * undefined — `state()` generates a fresh token.
     */
    presetState?: string
  ) {
    if (presetState) this.stateToken = presetState
  }

  // ----- where the redirect lands ---------------------------------------

  get redirectUrl(): string {
    // Single callback for all upstreams. We look up the (user, upstream)
    // pair from the state token in KV. The redirect_uri sent to the
    // upstream must match this exactly during DCR.
    return new URL(REDIRECT_PATH, this.env.PUBLIC_BASE_URL).toString()
  }

  get clientMetadata(): OAuthClientMetadata {
    return {
      client_name: 'ctxlayer',
      redirect_uris: [this.redirectUrl],
      grant_types: ['authorization_code', 'refresh_token'],
      response_types: ['code'],
      token_endpoint_auth_method: 'none',
      scope: this.preferredScope() ?? undefined
    }
  }

  // ----- state (PKCE / CSRF token) --------------------------------------

  state(): string {
    if (!this.stateToken) this.stateToken = crypto.randomUUID()
    return this.stateToken
  }

  async saveCodeVerifier(verifier: string): Promise<void> {
    const state = this.state()
    const stored: StoredVerifier = {
      verifier,
      userId: this.userId,
      upstreamId: this.upstream.id,
      createdAt: Math.floor(Date.now() / 1000)
    }
    await this.env.OAUTH_KV.put(verifierKey(state), JSON.stringify(stored), {
      expirationTtl: VERIFIER_TTL_SECONDS
    })
  }

  async codeVerifier(): Promise<string> {
    const state = this.state()
    const raw = await this.env.OAUTH_KV.get(verifierKey(state))
    if (!raw) throw new Error('oauth_verifier_missing_or_expired')
    const parsed = JSON.parse(raw) as StoredVerifier
    return parsed.verifier
  }

  // ----- client info (DCR) ---------------------------------------------

  async clientInformation(): Promise<OAuthClientInformationMixed | undefined> {
    const cfg = parseAuthConfig(this.upstream.auth_config)
    return cfg.oauth?.client_info as OAuthClientInformationMixed | undefined
  }

  async saveClientInformation(info: OAuthClientInformationFull): Promise<void> {
    const cfg = parseAuthConfig(this.upstream.auth_config)
    const nextOauth: OAuthAuthConfig = {
      ...(cfg.oauth ?? {}),
      client_info: info,
      client_id: info.client_id,
      client_secret: info.client_secret
    }
    const nextConfig: UpstreamAuthConfig = {
      ...cfg,
      // We store oauth client info as a typed-but-loose record alongside
      // the existing UpstreamAuthConfig fields. The shared schema knows
      // about `oauth: OauthAuthConfig` but its required fields don't match
      // what DCR returns (authorizeUrl/tokenUrl are server-discovered, not
      // admin-configured here). Keep the loose write — admin form never
      // round-trips this branch.
      oauth: nextOauth as unknown as UpstreamAuthConfig['oauth']
    }
    await patchUpstream(this.env, this.upstream.id, { authConfig: nextConfig })
    // Keep our in-memory row in sync for the rest of this request.
    this.upstream.auth_config = JSON.stringify(nextConfig)
  }

  // ----- tokens --------------------------------------------------------

  async tokens(): Promise<OAuthTokens | undefined> {
    const cred = await getUserCredential(this.env, this.userId, this.upstream.id)
    if (!cred || cred.kind !== 'oauth') return undefined
    try {
      const plaintext = await openSecret(
        { ciphertext: cred.ciphertext, iv: cred.iv, keyVersion: cred.key_version },
        this.env.ENCRYPTION_KEY
      )
      const stored = JSON.parse(plaintext) as StoredOAuthTokens
      return {
        access_token: stored.access_token,
        token_type: stored.token_type ?? 'Bearer',
        refresh_token: stored.refresh_token,
        scope: stored.scope,
        // Convert absolute expiry back to "seconds until expiry" so the
        // SDK's freshness check (`expires_in` <= 0 → refresh) keeps working.
        expires_in: stored.expires_at
          ? Math.max(0, stored.expires_at - Math.floor(Date.now() / 1000))
          : undefined
      }
    } catch (err) {
      console.error(`oauth tokens decrypt failed for upstream ${this.upstream.slug}:`, err)
      return undefined
    }
  }

  async saveTokens(tokens: OAuthTokens): Promise<void> {
    const now = Math.floor(Date.now() / 1000)
    const stored: StoredOAuthTokens = {
      access_token: tokens.access_token,
      token_type: tokens.token_type,
      refresh_token: tokens.refresh_token,
      scope: tokens.scope,
      expires_at: tokens.expires_in ? now + tokens.expires_in : undefined
    }
    const sealed = await sealSecret(JSON.stringify(stored), this.env.ENCRYPTION_KEY)
    await upsertUserCredential(this.env, this.userId, this.upstream.id, {
      kind: 'oauth',
      ciphertext: sealed.ciphertext,
      iv: sealed.iv,
      keyVersion: sealed.keyVersion
    })
  }

  // ----- redirect ------------------------------------------------------

  redirectToAuthorization(authorizationUrl: URL): void {
    // Capture for the HTTP handler to read after `auth()` returns
    // 'REDIRECT'. We can't actually redirect from inside a Worker
    // — we must return a 302 from the route layer.
    this.capturedRedirect = authorizationUrl
  }

  // ----- helpers -------------------------------------------------------

  private preferredScope(): string | null {
    const cfg = parseAuthConfig(this.upstream.auth_config)
    return cfg.oauth?.scopes?.join(' ') || null
  }
}

// ----- module-level helpers for routes --------------------------------

export async function readVerifierState(
  env: Env,
  stateToken: string
): Promise<StoredVerifier | null> {
  const raw = await env.OAUTH_KV.get(verifierKey(stateToken))
  return raw ? (JSON.parse(raw) as StoredVerifier) : null
}

export async function deleteVerifierState(env: Env, stateToken: string): Promise<void> {
  await env.OAUTH_KV.delete(verifierKey(stateToken))
}

function verifierKey(state: string): string {
  return `outbound:verifier:${state}`
}

function parseAuthConfig(json: string): UpstreamAuthConfig {
  if (!json) return {}
  try {
    return JSON.parse(json) as UpstreamAuthConfig
  } catch {
    return {}
  }
}
